### ISSUE TITLE
NoClassDefFoundError for BouncyCastle with Skuber 2.7.1

### ISSUE THREAD

**Issue by razzu** [hagay3/skuber#59] opened 2021-07-01 13:14 UTC
Hi,

I've been recently working on replacing an older version of Skuber (2.6.0, from the doriordan fork) to 2.7.1 (especially interested in some changes related to resource watches). 

When building my app with the 2.7.1 release, I get a `NoClassDefFound` error at runtime, related to BouncyCastle:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
	at skuber.api.security.TLS$.$anonfun$getTrustManagers$1(TLS.scala:60)
	at scala.Option.map(Option.scala:242)
	at skuber.api.security.TLS$.getTrustManagers(TLS.scala:59)
	at skuber.api.security.TLS$.buildSSLContext(TLS.scala:47)
	at skuber.api.security.TLS$.establishSSLContext(TLS.scala:36)
	at skuber.api.client.impl.KubernetesClientImpl$.apply(KubernetesClientImpl.scala:748)
	at skuber.api.client.package$.init(package.scala:218)
	at skuber.api.client.package$.init(package.scala:208)
	at skuber.api.client.package$.init(package.scala:196)
	at skuber.package$.k8sInit(package.scala:288)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 25 more
```

I think this might be fixed by the latest commit in master (https://github.com/hagay3/skuber/commit/5b28e55b02fd655d2dc18dd8d4c1abdee531aa29), but I haven't had the chance to try and build and run the code.

Are there any workarounds so we can get the current 2.7.1 release working, or is it better just to wait for the next release? I tried explicitly including bouncycastle as a dependency, but that then leads to a host of other issues and I think it's not really the way to go.

Thank you and thanks for working on this project!

**Comment by hagay3** [comment] 2021-07-01 13:43
Hi @razzu ,
Thank you for letting me know about the issue.
I will take the time and investigate how to fix the issue.

**Comment by razzu** [comment] 2021-07-02 07:31
If it helps, here's my build.sbt configuration, it's really just a minimal app testing out Skuber:

```
name := "test-skuber"
version := "0.1"
scalaVersion := "2.13.6"

libraryDependencies += "io.github.hagay3"           %% "skuber"          % "2.7.1"
libraryDependencies += "ch.qos.logback"              % "logback-classic" % "1.2.3"
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging"   % "3.9.3"
libraryDependencies += "com.github.pureconfig"      %% "pureconfig"      % "0.16.0"

ThisBuild / assemblyMergeStrategy  := {
  case PathList("module-info.class") => MergeStrategy.discard
  case x if x.endsWith("/module-info.class") => MergeStrategy.discard
  case x =>
    val oldStrategy = (ThisBuild / assemblyMergeStrategy).value
    oldStrategy(x)
}
```

**Comment by hagay3** [comment] 2021-07-03 21:13
Thanks for the information.
I think something is broken with that release.
I'm working on a fix here #60

**Comment by hagay3** [comment] 2021-07-07 21:02
Hi @razzu ,
The issue has been fixed, you can use now version `2.7.2`
Let me know if the issue is resolved so I can close it.
Working example:
```
name := "test-skuber"
version := "0.1"
scalaVersion := "2.13.6"

libraryDependencies += "io.github.hagay3"           %% "skuber"          % "2.7.2"
libraryDependencies += "ch.qos.logback"              % "logback-classic" % "1.2.3"
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging"   % "3.9.3"
libraryDependencies += "com.github.pureconfig"      %% "pureconfig"      % "0.16.0"

ThisBuild / assemblyMergeStrategy  := {
  case PathList("module-info.class") => MergeStrategy.discard
  case x if x.endsWith("/module-info.class") => MergeStrategy.discard
  case x =>
    val oldStrategy = (ThisBuild / assemblyMergeStrategy).value
    oldStrategy(x)
}
```

**Comment by razzu** [comment] 2021-07-08 12:49
Hi @hagay3 , thanks for looking into this! The `NoClassDefError` has indeed disappeared with the latest release, and the app now starts.

However, I'm getting the following error when I try to make the first API call using Skuber:
```
[INFO] [07/08/2021 15:45:55.562] [main] [skuber.api] Using following context for connecting to Kubernetes cluster: Context(Cluster(v1,https://127.0.0.1:51689,false,Some(Left(/Users/brinzea/.minikube/ca.crt))),CertAuth(clientCertificate=/Users/brinzea/.minikube/profiles/minikube/client.crt clientKey=/Users/brinzea/.minikube/profiles/minikube/client.key userName= ),Namespace(Namespace,v1,ObjectMeta(edge,,,,,,None,None,None,Map(),Map(),List(),0,None,None),None,None))
[INFO] [07/08/2021 15:45:56.314] [main] [skuber.api] [ { reqId=bdaf62f4-e660-41ba-b66f-9fe3220849ce} } - about to send HTTP request: GET https://127.0.0.1:51689/api/v1/namespaces/edge/configmaps/test-config]
[ERROR] [07/08/2021 15:45:56.500] [default-akka.actor.default-dispatcher-8] [akka://default/system/Materializers/StreamSupervisor-0/TLS-for-flow-1-1] Client/Server mode not yet set.
akka.actor.ActorInitializationException: akka://default/system/Materializers/StreamSupervisor-0/TLS-for-flow-1-1: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
	at akka.actor.ActorCell.create(ActorCell.scala:664)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:514)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:536)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IllegalStateException: Client/Server mode not yet set.
	at sun.security.ssl.SSLEngineImpl.kickstartHandshake(SSLEngineImpl.java:665)
	at sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:741)
	at akka.stream.impl.io.TLSActor.<init>(TLSActor.scala:165)
	at akka.stream.impl.io.TLSActor$.$anonfun$props$1(TLSActor.scala:40)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:91)
	at akka.actor.Props.newActor(Props.scala:226)
	at akka.actor.ActorCell.newActor(ActorCell.scala:616)
	at akka.actor.ActorCell.create(ActorCell.scala:643)
	... 9 more
```

I'm using Minikube to test this locally, and with the 2.7.0 version the call is succesful. The rest of the project is identical to what I tested when I originally opened this issue.

Here's a code snippet of what I'm doing, nothing too complicated:
```
    val k8s                = k8sInit
    val getConfigMapFuture = k8s.getInNamespace[ConfigMap](appConfig.configMapName, appConfig.namespace)
    getConfigMapFuture.onComplete {
        case Success(configMap) =>
          logger.info(s"Succesfully read ConfigMap: $configMap")
        case Failure(e) =>
          logger.warn(s"Failed to read ConfigMap, due to: $e")
    }
```

Let me know if you have any ideas or if you'd like me to open a new issue with this.

**Comment by hagay3** [comment] 2021-07-08 13:01
@razzu 
Can you try using `http` instead of `https` ?

[INFO] [07/08/2021 15:45:56.314] [main] [skuber.api] [ { reqId=bdaf62f4-e660-41ba-b66f-9fe3220849ce} } - about to send HTTP request: GET **https**://127.0.0.1:51689/api/v1/namespaces/edge/configmaps/test-config]

By the way, I tested with Kubernetes cluster and the connection is established.
You might have SSL issues since akka HTTP version is upgraded from `10.1.12` to `10.2.4` .
I saw that many changes have done around SSL between those releases.
https://doc.akka.io/docs/akka-http/current/release-notes/10.2.x.html

**Comment by hagay3** [comment] 2021-07-13 18:20
Closing this issue due to no response.
@razzu - you can ask me to reopen in case you still have issues.

**Closed as completed by hagay3** 2021-07-13 18:20 UTC
Labels: bug

**Comment by razzu** [comment] 2021-07-29 09:29
Hi @hagay3 , sorry for not following up on this.
I'm still seeing the issue, both locally and on an actual cluster. I'll open a separate issue.
